import React, { useEffect, useState } from 'react';
import StatsOverview from '../components/dashboard/StatsOverview';
import AttendanceTable from '../components/dashboard/AttendanceTable';
import AttendanceChart from '../components/dashboard/AttendanceChart';
import ArrivalHeatmap from '../components/dashboard/ArrivalHeatmap';
import { loadAttendanceRecords, loadRegisteredStudents, getAttendanceStats } from '../utils/attendanceAnalytics';

const PROFESSOR_NAME_KEY = 'overview_professor_name';

const Overview = () => {
  const [professorName, setProfessorName] = useState('Professor');
  const [editingName, setEditingName] = useState('');
  const [savedMessage, setSavedMessage] = useState('');
  const [reportStatus, setReportStatus] = useState('');
  const [stats, setStats] = useState({
    totalStudents: 0,
    presentToday: 0,
    lateArrivals: 0,
    blockchainLogs: 0,
  });

  useEffect(() => {
    const savedName = localStorage.getItem(PROFESSOR_NAME_KEY);
    if (savedName) {
      setProfessorName(savedName);
      setEditingName(savedName);
    } else {
      setEditingName('Professor');
    }
  }, []);

  useEffect(() => {
    const records = loadAttendanceRecords();
    const students = loadRegisteredStudents();
    const computed = getAttendanceStats(records, students);
    setStats({
      totalStudents: computed.totalStudents,
      presentToday: computed.presentToday,
      lateArrivals: computed.lateArrivals,
      blockchainLogs: computed.blockchainLogs,
      attendanceRate: computed.totalStudents > 0 ? Math.round((computed.presentToday / computed.totalStudents) * 100) : 0,
    });
  }, []);

  const saveProfessorName = () => {
    const trimmed = editingName.trim() || 'Professor';
    localStorage.setItem(PROFESSOR_NAME_KEY, trimmed);
    setProfessorName(trimmed);
    setSavedMessage('Professor name updated successfully.');
    setTimeout(() => setSavedMessage(''), 2500);
  };

  const generateReport = () => {
    const attendanceData = JSON.parse(localStorage.getItem('attendance_records') || '[]');
    const studentData = JSON.parse(localStorage.getItem('registeredStudents') || '[]');
    const now = new Date();
    const reportDate = now.toLocaleDateString();
    const reportTime = now.toLocaleTimeString();
    const summaryLines = [
      [`Report generated by:`, professorName],
      [`Generated on:`, reportDate, reportTime],
      [`Total registered students:`, studentData.length],
      [`Total attendance records:`, attendanceData.length],
      [`Current professor:`, professorName],
      [''],
      ['Student Name', 'Time', 'Date', 'Status', 'Transaction Hash']
    ];

    const rows = attendanceData.map((record) => [
      record.student || '',
      record.timestamp ? new Date(record.timestamp).toLocaleTimeString() : record.time || '',
      record.timestamp ? new Date(record.timestamp).toLocaleDateString() : record.date || '',
      record.status || '',
      record.fullHash || record.txHash || ''
    ]);
    const csvContent = [...summaryLines, ...rows].map((row) => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `attendance_report_${now.getTime()}.csv`;
    link.click();
    setReportStatus('Report downloaded successfully.');
    setTimeout(() => setReportStatus(''), 2500);
  };

  return (
    <>
      <div style={{
        marginBottom: 'var(--spacing-xl)',
        display: 'grid',
        gridTemplateColumns: '1fr',
        gap: 'var(--spacing-lg)',
        alignItems: 'flex-start'
      }}>
        <div>
          <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: '0.75rem',
            marginBottom: '0.5rem'
          }}>
            <span style={{
              padding: '4px 12px',
              backgroundColor: 'rgba(59, 130, 246, 0.1)',
              color: 'var(--accent-primary)',
              borderRadius: 'var(--radius-round)',
              fontSize: '0.75rem',
              fontWeight: '700',
              border: '1px solid rgba(59, 130, 246, 0.2)'
            }}>
              ACADEMIC YEAR 2026
            </span>
            <span style={{ color: 'var(--text-secondary)', fontSize: '0.75rem' }}>•</span>
            <span style={{ color: 'var(--text-secondary)', fontSize: '0.75rem' }}>Computer Science 101</span>
          </div>
          <h1 style={{
            fontSize: '2.5rem',
            fontWeight: '800',
            marginBottom: '0.5rem',
            letterSpacing: '-1px'
          }}>
            Welcome back, <span className="text-gradient">{professorName}</span>
          </h1>
          <p style={{ color: 'var(--text-secondary)', maxWidth: '600px', fontSize: '1rem' }}>
            Your smart attendance ecosystem is live. Access real student attendance insights, manage the roster, and generate reports for today’s class.
          </p>
        </div>

        <div style={{ display: 'grid', gap: '1rem' }}>
          <div style={{ padding: '1.5rem', borderRadius: '1rem', backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)', boxShadow: '0 20px 40px rgba(0,0,0,0.05)' }}>
            <div style={{ display: 'grid', gap: '0.75rem' }}>
              <label style={{ fontSize: '0.875rem', fontWeight: '700', color: 'var(--text-secondary)' }}>Professor name</label>
              <input
                type="text"
                value={editingName}
                onChange={(e) => setEditingName(e.target.value)}
                style={{
                  width: '100%',
                  padding: '0.85rem 1rem',
                  borderRadius: 'var(--radius-md)',
                  border: '1px solid var(--border-color)',
                  backgroundColor: 'var(--bg-secondary)',
                  color: 'var(--text-primary)'
                }}
              />
              <button
                onClick={saveProfessorName}
                className="btn-primary"
                style={{ padding: '0.75rem 1rem', width: '100%' }}
              >
                Save Name
              </button>
              <button
                onClick={generateReport}
                className="btn-primary"
                style={{ padding: '0.75rem 1.5rem', width: '100%' }}
              >
                Generate Report
              </button>
              {reportStatus && (
                <div style={{ color: '#4ade80', fontWeight: '700' }}>{reportStatus}</div>
              )}
              {savedMessage && (
                <div style={{ color: '#4ade80', fontWeight: '700' }}>{savedMessage}</div>
              )}
            </div>
          </div>
        </div>
      </div>

      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: '1rem',
        marginBottom: 'var(--spacing-lg)'
      }}>
        <div style={{ padding: '1.5rem', borderRadius: '1rem', backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)', boxShadow: '0 20px 40px rgba(0,0,0,0.05)' }}>
          <span style={{ display: 'block', color: 'var(--text-secondary)', fontSize: '0.85rem', fontWeight: '700', marginBottom: '0.65rem' }}>Registered Students</span>
          <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--text-primary)' }}>{stats.totalStudents}</div>
          <p style={{ marginTop: '0.75rem', color: 'var(--text-secondary)' }}>Total students available for attendance tracking.</p>
        </div>
        <div style={{ padding: '1.5rem', borderRadius: '1rem', backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)', boxShadow: '0 20px 40px rgba(0,0,0,0.05)' }}>
          <span style={{ display: 'block', color: 'var(--text-secondary)', fontSize: '0.85rem', fontWeight: '700', marginBottom: '0.65rem' }}>Attendance Rate</span>
          <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--text-primary)' }}>{stats.attendanceRate ?? 0}%</div>
          <p style={{ marginTop: '0.75rem', color: 'var(--text-secondary)' }}>Percentage of registered students present today.</p>
        </div>
        <div style={{ padding: '1.5rem', borderRadius: '1rem', backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)', boxShadow: '0 20px 40px rgba(0,0,0,0.05)' }}>
          <span style={{ display: 'block', color: 'var(--text-secondary)', fontSize: '0.85rem', fontWeight: '700', marginBottom: '0.65rem' }}>Late Arrivals</span>
          <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--text-primary)' }}>{stats.lateArrivals}</div>
          <p style={{ marginTop: '0.75rem', color: 'var(--text-secondary)' }}>Students marked late today.</p>
        </div>
        <div style={{ padding: '1.5rem', borderRadius: '1rem', backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)', boxShadow: '0 20px 40px rgba(0,0,0,0.05)' }}>
          <span style={{ display: 'block', color: 'var(--text-secondary)', fontSize: '0.85rem', fontWeight: '700', marginBottom: '0.65rem' }}>Attendance Logs</span>
          <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--text-primary)' }}>{stats.blockchainLogs}</div>
          <p style={{ marginTop: '0.75rem', color: 'var(--text-secondary)' }}>Total attendance events recorded.</p>
        </div>
      </div>

      <StatsOverview />

      <div style={{
        display: 'grid',
        gridTemplateColumns: '1.8fr 1.2fr',
        gap: 'var(--spacing-lg)',
        marginBottom: 'var(--spacing-lg)'
      }}>
        <AttendanceChart />
        <ArrivalHeatmap />
      </div>

      <AttendanceTable />

      <footer style={{
        marginTop: 'var(--spacing-xl)',
        padding: 'var(--spacing-lg) 0',
        borderTop: '1px solid var(--border-color)',
        display: 'flex',
        justifyContent: 'space-between',
        color: 'var(--text-secondary)',
        fontSize: '0.875rem'
      }}>
        <p>© 2026 Smart Attendance System • Blockchain Secured</p>
        <div style={{ display: 'flex', gap: '1.5rem' }}>
          <span>Privacy Policy</span>
          <span>System Status: Optimal</span>
        </div>
      </footer>
    </>
  );
};

export default Overview;
